#!/usr/bin/env python3
"""Assemble metrics for the MR-NIRP pilot (E21-E26 NIR, E31-E36 RGB).

Reuses scripts/repro/parse_metrics.py. Writes experiments/<exp>/metrics.json,
experiments/mrnirp_metrics.json, and reports/baseline_benchmark/mrnirp_pilot_summary.md.
"""
import json, os, sys

ROOT = "/home/lsg/rPPG"
sys.path.insert(0, os.path.join(ROOT, "scripts/repro"))
from parse_metrics import parse, to_markdown  # noqa: E402

EXP = os.path.join(ROOT, "experiments")

JOBS = [
    ("E21_MRNIRP_NIR_unsup",         "unsupervised", None),
    ("E22_MRNIRP_NIR_physnet",       "neural", "PURE->MR-NIRP NIR PhysNet"),
    ("E23_MRNIRP_NIR_tscan",         "neural", "PURE->MR-NIRP NIR TS-CAN"),
    ("E24_MRNIRP_NIR_deepphys",      "neural", "PURE->MR-NIRP NIR DeepPhys"),
    ("E25_MRNIRP_NIR_efficientphys", "neural", "PURE->MR-NIRP NIR EfficientPhys"),
    ("E26_MRNIRP_NIR_physformer",    "neural", "PURE->MR-NIRP NIR PhysFormer"),
    ("E31_MRNIRP_RGB_unsup",         "unsupervised", None),
    ("E32_MRNIRP_RGB_physnet",       "neural", "PURE->MR-NIRP RGB PhysNet"),
    ("E33_MRNIRP_RGB_tscan",         "neural", "PURE->MR-NIRP RGB TS-CAN"),
    ("E34_MRNIRP_RGB_deepphys",      "neural", "PURE->MR-NIRP RGB DeepPhys"),
    ("E35_MRNIRP_RGB_efficientphys", "neural", "PURE->MR-NIRP RGB EfficientPhys"),
    ("E36_MRNIRP_RGB_physformer",    "neural", "PURE->MR-NIRP RGB PhysFormer"),
]

combined, md = {}, []
for exp_id, kind, label in JOBS:
    log = os.path.join(EXP, exp_id, "run.log")
    if not os.path.exists(log):
        print(f"[skip] {exp_id}: no run.log"); continue
    res = parse(open(log, errors="ignore").read(), kind, label or "model")
    with open(os.path.join(EXP, exp_id, "metrics.json"), "w") as f:
        json.dump(res, f, indent=2)
    key = exp_id.replace("E2", "NIR_").replace("E3", "RGB_")
    if kind == "unsupervised":
        combined[exp_id] = res
        md.append((exp_id, res))
    else:
        combined.update(res)
        md.append((label, res))
    print(f"[ok] {exp_id}: {', '.join(sorted(res.keys())) if res else '(none)'}")

with open(os.path.join(EXP, "mrnirp_metrics.json"), "w") as f:
    json.dump(combined, f, indent=2)
print(f"[wrote] {os.path.join(EXP, 'mrnirp_metrics.json')}")

rep = os.path.join(ROOT, "reports", "baseline_benchmark")
os.makedirs(rep, exist_ok=True)
lines = ["# MR-NIRP Car (driving) pilot — PURE-pretrained cross-dataset\n",
         "Auto-generated by `scripts/mrnirp/build_mrnirp_summary.py`. First pilot on the partial",
         "download (usable = sessions with video + PulseOX GT), capped per-session frames.\n"]
for title, res in md:
    lines += [f"\n## {title}\n", to_markdown(res), ""]
out = os.path.join(rep, "mrnirp_pilot_summary.md")
open(out, "w").write("\n".join(lines) + "\n")
print(f"[wrote] {out}")
