#!/usr/bin/env python3
"""Assemble metrics for the full 42-subject UBFC run (E11-E16).

Reuses parse_metrics.py's regexes. For each experiment it:
  * parses experiments/<exp>/run.log,
  * writes experiments/<exp>/metrics.json,
and finally merges everything into experiments/all_metrics_full.json plus a
markdown summary at reports/baseline_benchmark/full_ubfc_summary.md.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from parse_metrics import parse, to_markdown  # noqa: E402

ROOT = "/home/lsg/rPPG"
EXP = os.path.join(ROOT, "experiments")

# (exp_id, kind, label)
JOBS = [
    ("E11_unsup_UBFCfull",               "unsupervised", None),
    ("E12_PURE2UBFC_physnet_full",       "neural", "PURE->UBFC PhysNet (full)"),
    ("E13_PURE2UBFC_tscan_full",         "neural", "PURE->UBFC TS-CAN (full)"),
    ("E14_PURE2UBFC_deepphys_full",      "neural", "PURE->UBFC DeepPhys (full)"),
    ("E15_PURE2UBFC_efficientphys_full", "neural", "PURE->UBFC EfficientPhys (full)"),
    ("E16_PURE2UBFC_physformer_full",    "neural", "PURE->UBFC PhysFormer (full)"),
]

combined = {}
md_sections = []
for exp_id, kind, label in JOBS:
    log = os.path.join(EXP, exp_id, "run.log")
    if not os.path.exists(log):
        print(f"[skip] {exp_id}: no run.log")
        continue
    text = open(log, errors="ignore").read()
    res = parse(text, kind, label or "model")
    with open(os.path.join(EXP, exp_id, "metrics.json"), "w") as f:
        json.dump(res, f, indent=2)
    if kind == "unsupervised":
        combined["unsupervised_UBFC_full"] = res
        md_sections.append(("Unsupervised (UBFC full, 42 subj)", res))
    else:
        combined.update(res)
        md_sections.append((label, res))
    have = ", ".join(sorted(res.keys())) if res else "(no metrics parsed)"
    print(f"[ok]   {exp_id}: {have}")

with open(os.path.join(EXP, "all_metrics_full.json"), "w") as f:
    json.dump(combined, f, indent=2)
print(f"[wrote] {os.path.join(EXP, 'all_metrics_full.json')}")

# markdown summary
report_dir = os.path.join(ROOT, "reports", "baseline_benchmark")
os.makedirs(report_dir, exist_ok=True)
lines = ["# UBFC full-set benchmark (42 subjects)\n",
         "Auto-generated by `scripts/repro/build_full_summary.py`.\n"]
for title, res in md_sections:
    lines.append(f"\n## {title}\n")
    lines.append(to_markdown(res))
    lines.append("")
out_md = os.path.join(report_dir, "full_ubfc_summary.md")
with open(out_md, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"[wrote] {out_md}")
